In [1]:
import tensorflow as tf
import numpy as np

# tf.debugging.set_log_device_placement(True)

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.executing_eagerly()

True

In [4]:
x0 = tf.constant(3)
x0

2022-02-03 20:28:33.988368: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-02-03 20:28:33.988573: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

Metal device set to: Apple M1


In [5]:
x0.dtype

tf.int32

In [6]:
x0.numpy()

3

In [7]:
# Tensors are immutable
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])
print(x1)
result1 = x1 + tf.constant(5.0) # a float can only be added to float
print(result1)
add1 = tf.add(x1, tf.constant(5.0))
print(add1)

tf.Tensor([1.1 2.2 3.3 4.4], shape=(4,), dtype=float32)
tf.Tensor([6.1 7.2 8.3 9.4], shape=(4,), dtype=float32)
tf.Tensor([6.1 7.2 8.3 9.4], shape=(4,), dtype=float32)


In [8]:
# 2D tensor
x_2D = tf.constant([[1, 2, 3, 4],[5, 6, 7, 9]])
print(x_2D)
## To convert an int tensor to float
x_2D_float = tf.cast(x_2D, tf.float32)
print(x_2D_float)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 9]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 9.]], shape=(2, 4), dtype=float32)


In [9]:
# matrix multiplication with different dimensions
x_1 = tf.constant([1,2,3,4], shape=[2,2])
x_2 = tf.constant([1,2,4,5,6,7], shape=[2,3])
x_multi_1_2 = tf.matmul(x_1, x_2)
x_multi_1_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 14, 18],
       [23, 30, 40]], dtype=int32)>

In [10]:
x_np_1 = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2,2,3])
x_np_1
x_np_2 = tf.constant(np.arange(2, 8, dtype=np.int32), shape=[2,3])
x_np_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

In [11]:
# Transpose a matrix
a = tf.constant(np.arange(1, 5, dtype=np.int32), shape=[2,2])
print(a)
a_transpose = tf.linalg.matrix_transpose(a)
print(a_transpose)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [12]:
# Transpose a 3 X 3 matrix
a_33 = tf.constant(np.arange(1,10, dtype=np.float), shape=[3,3])
print(a_33)
a_33_transpose = tf.linalg.matrix_transpose(a_33)
print(a_33_transpose)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]], shape=(3, 3), dtype=float64)


In [13]:
# Normalized Tensor
a_33_transpose_norm = tf.linalg.normalize(a_33_transpose, ord='euclidean', axis=None, name=None)
a_33_transpose_norm

(<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.05923489, 0.23693955, 0.41464421],
        [0.11846978, 0.29617444, 0.4738791 ],
        [0.17770466, 0.35540933, 0.53311399]])>,
 <tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[16.88194302]])>)

In [16]:
dataset = tf.data.Dataset.range(100)
def dataset_fn(ds):
    return ds.filter(lambda x: x < 5)
dataset = dataset.apply(dataset_fn)
list(dataset.as_numpy_iterator())

[0, 1, 2, 3, 4]

In [40]:
x=[]
for i in np.arange(9):
    x.append(i)
x = tf.constant(x, dtype=np.float, shape=[3,3])
print(x)

tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]], shape=(3, 3), dtype=float32)


In [55]:
value = 230
def interest(car):
    car = round(value * 0.02, 2)
    print('Car Interest Rate is',car,'%')

interest(value)

Car Interest Rate is 4.6 %
